adjective1 = input("enter an adjective (description): ")
noun1= input("enter a noun (person,place,thing):")
adjective2 = input("enter an adjective (description): ")
verb1= input("enter a verb ending with 'ing' ")
adjective3 = input("enter an adjective (description): ")

print(f"Today i went to a {adjective1} zoo.")
print(f"In an exbit, I saw a {noun1}.")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")