adjective = input("enter an adjective ")
place = input("enter a place ")
color = input("enter a colour ")
noun = input("enter a noun ")
adjective2 = input("enter an adjective ")
body_part = input("enter a body part ")
plural_noun = input("enter a plural noun ")
noun2 = input("enter a noun ")
object = input("enter an object ")
verb = input("enter a verb ")
celebrity = input("enter a celebrity ")
song = input("enter a song title ")
adjective3 = input("enter an adjective ")
plural_noun2 = input("enter a plural noun ")
food_item = input("enter any food ")
emotion = input("enter an emotion ")
planet_name = input("enter a planet name ")
noun3 = input("enter your name")
weapon = input("enter a weapon ")
verb2 = input("enter a verb ")

print(f"It was a(n) {adjective } day in {place } when suddenly, the sky turned {color }.")
print(f"Out of nowhere, a giant {noun } descended from the clouds, piloted by aliens with {adjective2 } {body_part } and glowing {plural_noun }.")
print(f"Their leader, General {noun2 }, stepped out and shouted, “We come in peace... unless you touch our {object }!")
print(f"Everyone panicked and started to {verb } while {celebrity } tried to calm the crowd by singing {song }.")
print(f"But it was too late. The aliens unleashed their {adjective3 } ray guns and turned all the {plural_noun2 }into {food_item }. Just when all hope seemed lost, {noun3} appeared with a {weapon} and yelled, Time to {verb2}!")
print(f"The aliens were so {emotion } that they fled back to {planet_name }, never to return again.")
