#A PYTHON PROGRAM THAT TAKES A NUMBER AS INPUT AND TELLS THE USER WHETHER IT ODD OR EVEN

number = int(input("INPUT A NUMBER AND I WILL TELL YOU IF IT EVEN OR ODD: "))

if number %2 == 0:
    print("THIS NUMBER IS AN EVEN NUMBER") 
else:
    print("THIS NUMBER IS AN ODD NUMBER")


